name: Intel OneAPI build and Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build_intel_champ_fparser:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: setup repo
      run: |
        wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
        sudo echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
        sudo apt-get update 
    - name: install
      run: |
        sudo apt-get install -y intel-oneapi-compiler-fortran
        sudo apt-get install -y intel-oneapi-compiler-dpcpp-cpp
        
    - name: Compile
      run: |
        source /opt/intel/oneapi/setvars.sh
        ./configure FC=ifort CC=icc FCFLAGS=-O2 CFLAGS=-O2
        make
        sudo make install
    - name: Check
      run: make check
        